import { useEffect, useMemo, useState } from "react";
import {
  BarChart3, Building2, Check, ChevronDown, Clock3, Copy, Download,
  ExternalLink, History, LayoutDashboard, LogOut, Menu, Moon, Plus,
  Search, SlidersHorizontal, Sparkles, Sun, Target, ThumbsDown,
  ThumbsUp, UserPlus, Users, X, Zap,
} from "lucide-react";
import { createUserWithEmailAndPassword, onAuthStateChanged, signInWithEmailAndPassword, signInWithPopup, signOut, type User } from "firebase/auth";
import { collection, doc, onSnapshot, query, orderBy } from "firebase/firestore";
import { httpsCallable } from "firebase/functions";
import { demoCompanies } from "./demo";
import { auth, db, firebaseConfigured, functions, googleProvider } from "./firebase";
import type { Company, Contact } from "./types";

type View = "dashboard" | "new" | "results" | "history";
type ResultTab = "companies" | "contacts" | "persona" | "approach";

const scoreClass = (score: number) => score >= 80 ? "score-good" : score >= 50 ? "score-mid" : "score-low";

function ScoreBadge({ score, kind }: { score: number; kind: "fit" | "timing" }) {
  return <span className={`score-badge ${scoreClass(score)} ${kind}`}>{kind === "fit" ? "FIT" : "TIMING"} <b>{score}</b></span>;
}

function Confidence({ value }: { value: Contact["confidence"] }) {
  const labels = { high: "Fiabilité élevée", medium: "Fiabilité moyenne", low: "Fiabilité faible", manual: "Manuel" };
  return <span className={`confidence ${value}`}><i />{labels[value]}</span>;
}

function Sidebar({ view, setView, open, close }: { view: View; setView: (v: View) => void; open: boolean; close: () => void }) {
  const nav = [
    ["dashboard", LayoutDashboard, "Vue d'ensemble"], ["new", Plus, "Nouvelle recherche"],
    ["results", Target, "Résultats"], ["history", History, "Historique"],
  ] as const;
  return <aside className={`sidebar ${open ? "open" : ""}`}>
    <div className="brand"><span className="brand-mark"><Target /></span><div><b>Prospect</b><small>INTELLIGENCE</small></div><button className="mobile-close" onClick={close}><X /></button></div>
    <nav>{nav.map(([key, Icon, label]) => <button key={key} className={view === key ? "active" : ""} onClick={() => { setView(key); close(); }}><Icon /><span>{label}</span>{key === "results" && <em>4</em>}</button>)}</nav>
    <div className="sidebar-bottom"><div className="plan"><span>PLAN DÉCOUVERTE</span><b>8 analyses restantes</b><div><i /></div><small>Réinitialisation dans 17 jours</small></div><button className="profile" onClick={()=>auth && signOut(auth)}><span>JD</span><div><b>Julien Dubois</b><small>julien@studio.fr</small></div><LogOut /></button></div>
  </aside>;
}

function Header({ title, dark, setDark, menu }: { title: string; dark: boolean; setDark: (v: boolean) => void; menu: () => void }) {
  return <header><button className="menu-btn" onClick={menu}><Menu /></button><div><p>ESPACE DE PROSPECTION</p><h1>{title}</h1></div><div className="header-actions"><label className="global-search"><Search /><input aria-label="Recherche globale" placeholder="Rechercher une entreprise…" /></label><button className="icon-btn" onClick={() => setDark(!dark)} aria-label="Changer le thème">{dark ? <Sun /> : <Moon />}</button><button className="avatar">JD</button></div></header>;
}

function Dashboard({ go }: { go: (view: View) => void }) {
  return <div className="page fade-in">
    <section className="hero"><div><span className="eyebrow"><Sparkles /> INTELLIGENCE COMMERCIALE</span><h2>Concentrez-vous sur les comptes<br /><strong>qui méritent votre attention.</strong></h2><p>Repérez les signaux d'achat, identifiez les bons décideurs et préparez une approche personnalisée — en quelques minutes.</p><button className="primary" onClick={() => go("new")}><Plus /> Lancer une analyse</button></div><div className="hero-radar"><span className="orbit o1"/><span className="orbit o2"/><span className="orbit o3"/><i className="dot d1"/><i className="dot d2"/><i className="dot d3"/><Target /></div></section>
    <section className="metrics"><article><span><Building2 /></span><div><small>COMPTES ANALYSÉS</small><b>148</b><em>+24 ce mois</em></div></article><article><span><Target /></span><div><small>FIT MOYEN</small><b>82<sup>/100</sup></b><em>+6 pts</em></div></article><article><span><Users /></span><div><small>DÉCIDEURS TROUVÉS</small><b>94</b><em>63 % des comptes</em></div></article><article><span><Zap /></span><div><small>SIGNAUX ACTIFS</small><b>37</b><em>12 cette semaine</em></div></article></section>
    <div className="dashboard-grid"><section className="panel"><div className="panel-head"><div><p>PRIORITÉS DU JOUR</p><h3>Comptes à contacter</h3></div><button onClick={() => go("results")}>Voir tous <ExternalLink /></button></div>{demoCompanies.slice(0,3).map((company,index) => <div className="priority-row" key={company.id}><span className="rank">0{index+1}</span><div className="company-icon">{company.name.slice(0,2).toUpperCase()}</div><div className="grow"><b>{company.name}</b><small>{company.sector} · {company.size} salariés</small></div><div className="tags">{company.signals.slice(0,1).map(s => <span key={s}>{s}</span>)}</div><ScoreBadge score={company.fitScore} kind="fit"/><ScoreBadge score={company.timingScore} kind="timing"/></div>)}</section>
    <section className="panel activity"><div className="panel-head"><div><p>ACTIVITÉ</p><h3>Derniers signaux</h3></div></div><div className="timeline"><div><i className="green"/><b>Levée de fonds détectée</b><p>Atlas Finance · Série A de 8 M€</p><small>Il y a 2 h</small></div><div><i className="blue"/><b>Nouvelle direction IT</b><p>Lumon Systems · Claire Moreau</p><small>Hier</small></div><div><i className="orange"/><b>Pic de recrutement</b><p>Nova Industrie · 12 postes tech</p><small>Il y a 2 j</small></div></div></section></div>
  </div>;
}

function NewSearch({ onLaunch }: { onLaunch: () => void }) {
  const [step, setStep] = useState(1);
  const [entry, setEntry] = useState("");
  const [type, setType] = useState<"company"|"keywords">("company");
  return <div className="page narrow fade-in"><div className="steps"><span className="done"><i><Check /></i>Point d'entrée</span><b/><span className={step === 2 ? "done" : ""}><i>2</i>Profil de besoin</span><b/><span><i>3</i>Validation</span></div>
    {step === 1 ? <section className="form-card"><div className="form-title"><span><Search /></span><div><p>ÉTAPE 1 SUR 3</p><h2>Que souhaitez-vous explorer ?</h2><small>Donnez-nous un point de départ. Nous identifierons l'écosystème pertinent.</small></div></div><div className="choice-grid"><button className={type === "company" ? "selected" : ""} onClick={() => setType("company")}><Building2/><b>Entreprise ou groupe</b><small>Explorez son écosystème, ses filiales et concurrents</small></button><button className={type === "keywords" ? "selected" : ""} onClick={() => setType("keywords")}><Sparkles/><b>Mots-clés sectoriels</b><small>Découvrez des entreprises sur un marché précis</small></button></div><label className="field"><span>{type === "company" ? "NOM DE L'ENTREPRISE" : "MOTS-CLÉS"}</span><div><Search/><input value={entry} onChange={e => setEntry(e.target.value)} placeholder={type === "company" ? "Ex. Doctolib, LVMH, Qonto…" : "Ex. cybersécurité, retail durable…"}/></div><small>Minimum 2 caractères</small></label><div className="form-actions"><span/><button className="primary" disabled={entry.trim().length < 2} onClick={() => setStep(2)}>Continuer <span>→</span></button></div></section> : <NeedForm onBack={() => setStep(1)} onLaunch={onLaunch}/>}</div>;
}

function NeedForm({ onBack, onLaunch }: { onBack: () => void; onLaunch: () => void }) {
  const [loading,setLoading] = useState(false);
  const launch = () => { setLoading(true); setTimeout(onLaunch, 1100); };
  return <section className="form-card"><div className="form-title"><span><SlidersHorizontal /></span><div><p>ÉTAPE 2 SUR 3</p><h2>Affinez votre cible idéale</h2><small>Ces critères alimentent directement les scores de Fit et de Timing.</small></div></div><div className="fields-grid"><label className="field full"><span>SOLUTION PROPOSÉE</span><textarea defaultValue="Plateforme SaaS de pilotage et sécurisation des opérations IT" /></label><label className="field"><span>TAILLE MINIMUM</span><input type="number" defaultValue="50" /></label><label className="field"><span>TAILLE MAXIMUM</span><input type="number" defaultValue="1000" /></label><label className="field"><span>ZONE GÉOGRAPHIQUE</span><select defaultValue="France"><option>France</option><option>France & Benelux</option><option>Europe</option></select></label><label className="field"><span>BUDGET TYPE</span><select defaultValue="20–50 k€"><option>10–20 k€</option><option>20–50 k€</option><option>50–100 k€</option></select></label><label className="field full"><span>RÔLES DÉCIDEURS</span><div className="tag-input"><span>DSI <X/></span><span>CTO <X/></span><span>VP Engineering <X/></span><input placeholder="Ajouter un rôle…"/></div></label><label className="field full"><span>SIGNAUX D'ACHAT</span><div className="check-grid"><label><input type="checkbox" defaultChecked/> Levée de fonds</label><label><input type="checkbox" defaultChecked/> Recrutement tech</label><label><input type="checkbox" defaultChecked/> Changement de stack</label><label><input type="checkbox"/> Nouvelle direction</label></div></label><label className="field"><span>ENTREPRISES POUR L'IA</span><input type="number" min="1" max="25" defaultValue="5"/><small>Persona + approche pour les 5 meilleurs Fit</small></label></div><div className="quota-note"><Sparkles/><div><b>Estimation de l'analyse</b><span>Jusqu'à 5 personas et 5 plans d'approche · environ 2 à 4 minutes</span></div></div><div className="form-actions"><button className="secondary" onClick={onBack}>← Retour</button><button className="primary" onClick={launch} disabled={loading}>{loading ? <><span className="spinner"/> Analyse en cours…</> : <>Lancer l'analyse <Sparkles/></>}</button></div></section>;
}

function Results({ companies = demoCompanies }: { companies?: Company[] }) {
  const [tab,setTab] = useState<ResultTab>("companies");
  const [selected,setSelected] = useState<Company|null>(null);
  const tabs: Array<[ResultTab,string,number?]> = [["companies","Entreprises",4],["contacts","Décideurs",4],["persona","Buyer Persona"],["approach","Plan d'approche"]];
  return <div className="page fade-in"><div className="results-intro"><div><span className="eyebrow"><Check/> ANALYSE TERMINÉE</span><h2>Cybersécurité · ETI France</h2><p>{companies.length} entreprises qualifiées · mise à jour en temps réel</p></div><button className="secondary"><Download/> Exporter CSV</button></div><div className="tabs">{tabs.map(([id,label,count]) => <button className={tab === id ? "active" : ""} key={id} onClick={() => setTab(id)}>{label}{count && <span>{count}</span>}</button>)}</div>{tab === "companies" && <Companies companies={companies} select={setSelected}/>} {tab === "contacts" && <Contacts companies={companies}/>} {tab === "persona" && <Persona/>} {tab === "approach" && <Approach/>}{selected && <CompanyDrawer company={selected} close={() => setSelected(null)}/>}</div>;
}

function Companies({ companies, select }: { companies: Company[]; select: (c: Company) => void }) {
  const [sort,setSort] = useState<"fit"|"timing">("fit");
  const sorted = useMemo(() => [...companies].sort((a,b) => sort === "fit" ? b.fitScore-a.fitScore : b.timingScore-a.timingScore),[companies,sort]);
  return <section className="panel results-panel"><div className="filterbar"><label><Search/><input placeholder="Rechercher dans les résultats"/></label><button><SlidersHorizontal/> Filtres <span>2</span></button><label className="sort">Trier par <select value={sort} onChange={e => setSort(e.target.value as "fit"|"timing")}><option value="fit">Fit Score</option><option value="timing">Timing Score</option></select></label></div><div className="company-table"><div className="table-head"><span>ENTREPRISE</span><span>SIGNAUX ACTIFS</span><span>CRM</span><span>SCORES</span><span/></div>{sorted.map(company => <button className="company-row" key={company.id} onClick={() => select(company)}><span className="company-cell"><i>{company.name.slice(0,2).toUpperCase()}</i><span><b>{company.name}</b><small>{company.sector} · {company.size} salariés · {company.geo}</small></span></span><span className="signal-cell">{company.signals.slice(0,2).map(s => <em key={s}>{s}</em>)}</span><span><em className={`crm ${company.crmStatus}`}>{company.crmStatus === "new" ? "Nouveau" : company.crmStatus === "already_in_pipe" ? "En cours" : "Exclu"}</em></span><span className="scores"><ScoreBadge score={company.fitScore} kind="fit"/><ScoreBadge score={company.timingScore} kind="timing"/></span><span className="arrow">→</span></button>)}</div></section>;
}

function Contacts({ companies }: { companies: Company[] }) { const contacts = companies.flatMap(c => c.contacts.map(contact => ({...contact,company:c.name}))); return <div className="contact-grid">{contacts.map(contact => <article className="contact-card" key={contact.id}><div className="contact-top"><span>{contact.name.split(" ").map(n=>n[0]).join("")}</span><div><b>{contact.name}</b><small>{contact.role}</small></div><button><ExternalLink/></button></div><p><Building2/> {contact.company}<span>{contact.seniority}</span></p>{contact.email && <a href={`mailto:${contact.email}`}>{contact.email}<Copy/></a>}<div className="contact-foot"><Confidence value={contact.confidence}/><small>Vérifié le {contact.verifiedAt}</small></div><div className="vote"><span>Ce contact est-il pertinent ?</span><button aria-label="Pertinent"><ThumbsUp/></button><button aria-label="Non pertinent"><ThumbsDown/></button></div></article>)}<button className="add-contact"><UserPlus/><b>Ajouter un contact</b><span>Compléter manuellement la liste</span></button></div>; }

function Persona() { return <div className="persona-layout"><section className="persona-profile"><span className="persona-avatar">DSI</span><p>BUYER PERSONA PRINCIPAL</p><h2>La DSI transformatrice</h2><em>Direction IT · ETI 100–1 000 collaborateurs</em><blockquote>« Je dois accélérer la transformation sans compromettre la sécurité ni perdre mes équipes en route. »</blockquote><div className="persona-tags"><span>Pragmatique</span><span>Orientée risque</span><span>Influente</span></div></section><section className="persona-details"><article><h3><Target/>Motivations</h3><ul><li>Réduire les incidents et la dette technique</li><li>Donner de la visibilité au COMEX</li><li>Industrialiser sans rigidifier les équipes</li></ul></article><article><h3><X/>Freins & objections</h3><ul><li>Temps d'intégration et dépendance éditeur</li><li>Adoption par les équipes opérationnelles</li><li>ROI difficile à démontrer à court terme</li></ul></article><article><h3><BarChart3/>KPIs suivis</h3><div className="kpis"><span>MTTR</span><span>Taux d'incidents</span><span>Coût / service</span><span>Time-to-market</span></div></article><article><h3><Sparkles/>Vocabulaire à privilégier</h3><div className="quote-list"><span>Maîtrise du risque</span><span>Visibilité consolidée</span><span>Déploiement progressif</span></div></article></section></div>; }

function Approach() { const [copied,setCopied]=useState(false); return <div className="approach-layout"><section className="panel approach-main"><div className="approach-company"><span>LU</span><div><p>PLAN RECOMMANDÉ</p><h2>Lumon Systems</h2></div><ScoreBadge score={94} kind="fit"/></div><div className="angle"><span><Zap/></span><div><p>ANGLE D'ACCROCHE</p><h3>Transformer la croissance de l'équipe IT en levier de maîtrise opérationnelle</h3><small>Le recrutement accéléré et la refonte SI créent une fenêtre de décision forte.</small></div></div><h3 className="section-label">SÉQUENCE EN 3 ÉTAPES</h3><div className="sequence"><article><i>01</i><div><b>Email court et contextualisé</b><span>Jour 1 · 08:30</span><p>Faire écho aux recrutements récents et proposer un benchmark de maturité.</p></div></article><article><i>02</i><div><b>Connexion LinkedIn</b><span>Jour 3</span><p>Invitation sobre, sans pitch, rappelant le sujet opérationnel.</p></div></article><article><i>03</i><div><b>Relance avec preuve</b><span>Jour 7</span><p>Partager un résultat client comparable et proposer 20 minutes.</p></div></article></div></section><aside className="panel draft"><div className="panel-head"><div><p>BROUILLON D'EMAIL</p><h3>Prêt à personnaliser</h3></div><button onClick={() => {navigator.clipboard?.writeText("Bonjour Claire…");setCopied(true)}}>{copied ? <Check/> : <Copy/>} {copied ? "Copié" : "Copier"}</button></div><div className="email"><p><b>Objet :</b> Lumon × maîtrise des opérations IT</p><p>Bonjour Claire,</p><p>J’ai vu que Lumon renforçait fortement ses équipes tech en parallèle de sa refonte SI.</p><p>Dans ce contexte, plusieurs DSI nous sollicitent pour retrouver une visibilité consolidée sans ralentir les équipes opérationnelles.</p><p>Nous avons récemment aidé une ETI SaaS comparable à réduire son MTTR de 28 % en trois mois.</p><p>Est-ce un sujet d’actualité chez vous ? Je serais ravi de partager le retour d’expérience en 20 minutes.</p><p>Bien à vous,<br/>Julien</p></div><div className="tone"><span>TON</span><b>Direct · Expert · Sans pression</b></div></aside></div>; }

function CompanyDrawer({ company, close }: { company: Company; close: () => void }) { return <><button className="overlay" onClick={close} aria-label="Fermer"/><aside className="drawer"><button className="drawer-close" onClick={close}><X/></button><div className="drawer-title"><span>{company.name.slice(0,2).toUpperCase()}</span><div><p>FICHE ENTREPRISE</p><h2>{company.name}</h2><small>{company.sector} · {company.size} salariés · {company.geo}</small></div></div><div className="drawer-scores"><div><ScoreBadge score={company.fitScore} kind="fit"/><b>Excellent alignement</b></div><div><ScoreBadge score={company.timingScore} kind="timing"/><b>Fenêtre active</b></div></div><h3>Pourquoi ces scores ?</h3><div className="breakdown">{Object.entries(company.fitBreakdown).map(([label,value]) => <div key={label}><span>{label}</span><i><b style={{width:`${value*100}%`}}/></i><em>{Math.round(value*100)}%</em></div>)}</div><h3>Signaux détectés</h3><div className="drawer-signals">{company.signals.map(signal => <span key={signal}><Zap/>{signal}</span>)}</div><h3>Décideurs</h3>{company.contacts.length ? company.contacts.map(c => <div className="drawer-contact" key={c.id}><span>{c.name.split(" ").map(n=>n[0]).join("")}</span><div><b>{c.name}</b><small>{c.role}</small></div><Confidence value={c.confidence}/></div>) : <p className="empty">Aucun décideur trouvé — vous pouvez en ajouter un manuellement.</p>}<button className="primary full">Préparer une approche <Sparkles/></button></aside></>; }

function HistoryView({ go }: { go: (v: View) => void }) { return <div className="page fade-in"><div className="results-intro"><div><span className="eyebrow"><Clock3/> ARCHIVES</span><h2>Historique des recherches</h2><p>Retrouvez vos analyses et relancez une recherche en un clic.</p></div><button className="primary" onClick={() => go("new")}><Plus/>Nouvelle recherche</button></div><section className="panel history-list">{[["Cybersécurité · ETI France","14 août 2026","4 comptes","82 fit moyen"],["Retail durable · Benelux","8 août 2026","17 comptes","76 fit moyen"],["SaaS RH · France","29 juillet 2026","24 comptes","71 fit moyen"]].map((row,i)=><button key={row[0]} onClick={()=>go("results")}><span className="history-icon"><Search/></span><span className="grow"><b>{row[0]}</b><small>{row[1]}</small></span><em>{row[2]}</em><em>{row[3]}</em><span>→</span></button>)}</section></div>; }

function AuthScreen() {
  const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [signup,setSignup]=useState(false); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
  const submit = async () => { if (!auth) return; setBusy(true); setError(""); try { if (signup) await createUserWithEmailAndPassword(auth,email,password); else await signInWithEmailAndPassword(auth,email,password); } catch { setError("Connexion impossible. Vérifiez vos identifiants."); } finally { setBusy(false); } };
  return <div className="auth-page"><section><div className="auth-brand"><span><Target/></span><b>Prospect Intelligence</b></div><p className="eyebrow"><Sparkles/>PROSPECTION AUGMENTÉE</p><h1>Les bons comptes.<br/><strong>Au bon moment.</strong></h1><p>Transformez les signaux faibles en opportunités commerciales concrètes.</p><div className="auth-proof"><span><Check/>Scoring explicable</span><span><Check/>Décideurs qualifiés</span><span><Check/>Approches personnalisées</span></div></section><form onSubmit={e=>{e.preventDefault();void submit()}}><p>ESPACE SÉCURISÉ</p><h2>{signup ? "Créer votre compte" : "Bon retour parmi nous"}</h2><small>{signup ? "Lancez votre première analyse." : "Connectez-vous à votre espace de prospection."}</small><label>EMAIL<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="vous@entreprise.fr"/></label><label>MOT DE PASSE<input type="password" required minLength={6} value={password} onChange={e=>setPassword(e.target.value)} placeholder="••••••••"/></label>{error && <em>{error}</em>}<button className="primary" disabled={busy}>{busy ? "Connexion…" : signup ? "Créer mon compte" : "Se connecter"}</button><div className="or"><span/>OU<span/></div><button type="button" className="google" onClick={()=>auth && signInWithPopup(auth,googleProvider)}>G&nbsp;&nbsp; Continuer avec Google</button><button type="button" className="switch-auth" onClick={()=>setSignup(!signup)}>{signup ? "Déjà inscrit ? Se connecter" : "Pas encore de compte ? Créer un compte"}</button></form></div>;
}

export default function App() {
  const [view,setView] = useState<View>("dashboard"); const [dark,setDark]=useState(false); const [menu,setMenu]=useState(false); const [user,setUser]=useState<User|null|undefined>(firebaseConfigured ? undefined : null); const [searchId,setSearchId]=useState<string|null>(null); const [liveCompanies,setLiveCompanies]=useState<Company[]>(demoCompanies); const [progress,setProgress]=useState<number|null>(null);
  useEffect(()=>{ if(!auth) return; return onAuthStateChanged(auth,setUser); },[]);
  useEffect(()=>{ if(!db || !searchId) return; const unsubSearch=onSnapshot(doc(db,"searches",searchId),snap=>setProgress(snap.data()?.progress ?? 0)); const unsubCompanies=onSnapshot(query(collection(db,"searches",searchId,"companies"),orderBy("fitScore","desc")),snap=>{ const values=snap.docs.map(item=>{const data=item.data();return {id:item.id,name:String(data.name??"Entreprise"),sector:String(data.sector??"Non renseigné"),size:Number(data.size??0),geo:String(data.geo??"Non renseigné"),website:String(data.website??""),fitScore:Number(data.fitScore??0),timingScore:Number(data.timingScore??0),crmStatus:(data.crmStatus??"new") as Company["crmStatus"],fitBreakdown:(data.fitBreakdown??{}) as Record<string,number>,timingBreakdown:(data.timingBreakdown??{}) as Record<string,number|string>,contacts:[],signals:[]};}); if(values.length) setLiveCompanies(values); }); return ()=>{unsubSearch();unsubCompanies();}; },[searchId]);
  const launchSearch = async () => { if(!functions){ await new Promise(resolve=>setTimeout(resolve,900)); setView("results"); return; } const call=httpsCallable(functions,"discoverCompanies"); const response=await call({entryType:"keywords",entryValue:"cybersécurité ETI",needProfile:{solutionType:"Plateforme SaaS de pilotage et sécurisation des opérations IT",targetSizeMin:50,targetSizeMax:1000,geoZones:["France"],sectors:[],budgetType:"20–50 k€",buySignals:["Levée de fonds","Recrutement tech"],decisionRoles:["DSI","CTO"],maxEntitiesForLLM:5}}); const payload=response.data as {success:boolean;data?:{searchId:string}}; if(payload.data?.searchId)setSearchId(payload.data.searchId); setView("results"); };
  const titles: Record<View,string> = {dashboard:"Bonjour Julien 👋",new:"Nouvelle recherche",results:"Résultats de l'analyse",history:"Historique"};
  if(firebaseConfigured && user === undefined) return <div className="auth-loading"><span className="spinner"/>Chargement sécurisé…</div>;
  if(firebaseConfigured && !user) return <AuthScreen/>;
  return <div className={dark ? "app dark" : "app"}><Sidebar view={view} setView={setView} open={menu} close={()=>setMenu(false)}/><main><Header title={titles[view]} dark={dark} setDark={setDark} menu={()=>setMenu(true)}/>{progress !== null && progress < 100 && <div className="progress-line"><i style={{width:`${progress}%`}}/><span>Analyse en cours · {progress}%</span></div>}{view === "dashboard" && <Dashboard go={setView}/>} {view === "new" && <NewSearch onLaunch={()=>{void launchSearch()}}/>} {view === "results" && <Results companies={liveCompanies}/>} {view === "history" && <HistoryView go={setView}/>}</main></div>;
}
